api_platform:
    title: 'E-commerce API'
    description: 'API for managing products'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json']
